sonar.projectKey=github-actions
sonar.projectName=GitHub Actions React App
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

