sonar.projectKey=github-actions    # Must match the project key you created in SonarQube
sonar.projectName=GitHub Actions React App
sonar.sources=.
sonar.host.url=${env.SONAR_HOST_URL}
sonar.login=${env.SONAR_TOKEN}
