name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  
jobs:
  # Stage 1: Checkout
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Repository
        run: echo "Runner is working fine!"

  # Stage 2: SonarQube Scan
  sonar:
    runs-on: self-hosted
    needs: checkout
    steps:
      - uses: actions/checkout@v4

      #Sonarqube quality scan on the files
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.0
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      #Sonarqube quality gate check 
      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        continue-on-error: true
        with:
          args: >
            -Dsonar.projectKey=github-actions
            -Dsonar.projectName="GitHub Actions React App"
            -Dsonar.sources=.

  # Stage 3: React Build
  build:
    runs-on: self-hosted
    needs: sonar
    steps:
      - uses: actions/checkout@v4

      # Stage 3.1: Install dependencies
      - name: Install dependencies
        run: npm install

      # Stage 3.2: Build React app
      - name: Build project
        run: npm run build

      # Stage 3.3: Upload build as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  # Stage 4: Trivy File Scan
  trivy-files:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy FS Scan
        run: trivy fs . --exit-code 0 --no-progress --format table > trivy-fs-report.txt

      - name: Upload Trivy FS Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.txt
          
  docker_build:
    runs-on: self-hosted
    needs: trivy-files
    steps:
      - uses: actions/checkout@v4

      - name: Dokcer build
        run: docker build -t sivahere/git-actions-img .
        
      # Stage 7: Trivy Image Scan
  trivy-image:
    runs-on: self-hosted
    needs: docker_build
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Image Scan
        run: |
          trivy image sivahere/git-actions-img:latest --exit-code 0 --no-progress --format table > trivy-image-report.txt

      - name: Upload Trivy Image Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.txt

      # Stage 8: Push to Docker Hub
  dockerhub-push:
    runs-on: self-hosted
    needs: trivy-image
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push sivahere/git-actions-img:latest

    
