name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    #stage 1:Checkout
    - uses: actions/checkout@v4
    - name: Checkout Repository
      run: echo "Runner is working fine!"

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v2.0.0
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        
    - name: SonarQube Quality Gate check
      uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      continue-on-error: true
      with:
          args: >
            -Dsonar.projectKey=github-actions
            -Dsonar.projectName="GitHub Actions React App"
            -Dsonar.sources=.
      
