name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      #stage 1:Checkout
      - uses: actions/checkout@v4
      - name: Checkout Repository
        run: echo "Runner is working fine!"

      #Sonarqube quality scan on the files
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.0
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      #Sonarqube quality gate check 
      - name: SonarQube Quality Gate check
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        continue-on-error: true
        with:
          args: >
            -Dsonar.projectKey=github-actions
            -Dsonar.projectName="GitHub Actions React App"
            -Dsonar.sources=.

      # Stage 3.1: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'    # React apps typically use Node 16/18/20

      # Stage 3.2: Install dependencies
      - name: Install dependencies
        run: npm install

      # Stage 3.3: Build React app
      - name: Build project
        run: npm run build

      # Stage 3.4: Upload build as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/
