name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Say hello
        run: echo "✅ Runner is working fine!"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

