name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: my-ubuntu-runner   # since you’re using your Ubuntu t2.medium runner
    steps:
      # Stage 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4
