name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Print runner context
        run: |
          echo "Runner labels: ${{ runner.labels }}"
          echo "Workspace: $GITHUB_WORKSPACE"


